apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: sample-java
spec: 
 replicas: 2 
 strategy: 
  type: Recreate 
 selector: 
  matchLabels: 
   app: my-app-java
 template: 
   metadata: 
    labels: 
     app: my-app-java 
     env: prod 
   spec: 
    containers: 
    - name: my-deployment-container 
      image: docker1otsi/docker-java
