apiVersion: v1
kind: Service
metadata:
 name: sample-pod-java
spec:
 type: NodePort
 selector:
   app: my-app-java
   env: prod
 ports:
 - nodePort: 32411
   protocol: TCP
   port: 80
   targetPort: 80
